"""Migração inicial

Revision ID: 5f87c7272bf3
Revises: 3859f5fb7f93
Create Date: 2024-10-29 13:58:50.585435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f87c7272bf3'
down_revision = '3859f5fb7f93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
